runtime: php
env: flex

runtime_config:
  document_root: public

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/php/configuring-your-app-with-app-yaml
# manual_scaling:
#   instances: 1
# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10


env_variables:
  APP_LOG: errorlog
  APP_KEY: base64:FUHXdWiOS+8zOdX5L7wWRVwOaisJh3iUN5ZKW+/pkOs=
  FIREBASE_CREDENTIALS: firebase_credentials.json
  GOOGLE_APPLICATION_CREDENTIALS: firebase_credentials.json
  GOOGLE_MAPS_API_KEY: AIzaSyBGOjv52IeGuG5y8WOHV4UbFkB6PIFBTtM
  projectId: edrop-6c149